export enum Permission {
  ViewSchedules = 'ViewSchedules',
  ViewWeekendSpeakers = 'ViewWeekendSpeakers',
  UpdateMaintenanceSchedules = 'UpdateMaintenanceSchedules',
  UpdateCustomAssignments = 'UpdateCustomAssignments',
  UpdateCongregation = 'UpdateCongregation',
  ViewUsers = 'ViewUsers',
  ViewUsersMinimal = 'ViewUsersMinimal',
  ViewReportsAll = 'ViewReportsAll',
  ViewReportsGroup = 'ViewReportsGroup',
  UpdateUsers = 'UpdateUsers',
  UpdateReports = 'UpdateReports',
  UpdateAttendance = 'UpdateAttendance',
  ViewSummary = 'ViewSummary',
  UpdateTerritory = 'UpdateTerritory',
  ViewTerritory = 'ViewTerritory',
  ManagePermissions = 'ManagePermissions',
  SendPush = 'SendPush',
  ViewUsersNotPublishing = 'ViewUsersNotPublishing',
  ViewEmergencycontacts = 'ViewEmergencycontacts',
}
